includes:
- ../configs/captioning/youcookII/butd.yml
task_attributes:
    captioning:
        datasets:
        - youcookII
        dataset_size_proportional_sampling: true
        dataset_attributes:
            youcookII:
                data_root_dir: /home/ascott/data/pythia/youcookII_features
                image_depth_first: false
                fast_read: false
                image_features:
                    train:
                    - training_features_vmb,training_features_resnet
                    val:
                    - validation_features_vmb,validation_features_resnet
                    test:
                    - test_features_vmb,test_features_resnet
                imdb_files:
                    train:
                    - imdb_youcookII_training.npy
                    val:
                    - imdb_youcookII_validation.npy
                    test:
                    - imdb_youcookII_test.npy
                features_max_len: 100
                processors:
                  text_processor:
                    type: vocab
                    params:
                      max_length: 52
                      vocab:
                        type: intersected
                        embedding_name: glove.6B.300d
                        vocab_file: youcookII_vocabulary.txt
                      preprocessor:
                        type: simple_sentence
                        params: {}
                  caption_processor:
                    type: caption
                    params:
                      vocab:
                        type: intersected
                        embedding_name: glove.6B.300d
                        vocab_file: youcookII_vocabulary.txt
                min_captions_per_img: 1
                return_info: false
                # Return OCR information
                use_ocr: false
                # Return spatial information of OCR tokens if present
                use_ocr_info: false
training_parameters:
    monitored_metric: coco_caption_bleu4
    metric_minimize: false
